<meta charset="utf-8">
<script>

	// Когда знаешь, что здесь у тебя будет ошибка, но тебе нужно, чтобы программа все равно выполнилась полностью. Ошибки не будет по итогу, но в консоль можно вывести, что это за ошибка. 

	try {
		a = b;
	}

	catch (ex) { // если возникла ошибка
		console.log('Возникла ошибка: ' + ex);
	}

	//Бывает такое, что какая-то объект приходит из сервера и нужно проделать работу с ней. Представим, что введенные данные это из сервера {"a": "2"}

	var str = prompt('Введите JSON:');

	try {
		var json = JSON.parse(str);
	} catch (ex) { 
		alert('Введен некорректный JSON');
	} console.log(json);

	//Третий пример, когда нужно перехватить не числовое значение

	function calcBirthYear() {

		var age = prompt('Введите ваш возраст');
		var birthYear = new Date().getFullYear() - age;

		if (isNaN(birthYear)) {
			throw('не числовое значение'); //это исключение, которое перехватывает catch
		} else if (age !== null) {
			alert('Ваш год рождения: ' + birthYear);
		}
	}

	try {
		calcBirthYear();
	} catch (ex) {
		alert('Ошибка ввода: ' + ex);
	}

	//Заключение: такие исключения можно использовать только в случаях, если 1)функции пока не переданы параметры; 2)переданы параметры не того типа
	//Когда пользователь ввел некорректное значение, используем другие более мягкие методы
	
</script>